<a href="https://colab.research.google.com/github/mochamadprayitno22-commits/data-project-agus-bigquery-telco-churn/blob/main/AGGREGATION_GROUP_BY_HAVING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a id="A"></a>
# <b>A. <span style='color:#0B2F9F'><code>AGGREGATION</code></b>

Fungsi agregat atau <b>Aggregation</b> adalah fungsi yang melakukan perhitungan pada sekumpulan nilai dan mengembalikan satu nilai hasil perhitungan tersebut. Fungsi agregat SQL yang paling umum digunakan adalah:
<br><br>
<table border="1">
    <tr>
        <th>Fungsi Agregat</th>
        <th>Deskripsi</th>
    </tr>
    <tr>
        <td><b>MIN( )</b></td>
        <td>Mengembalikan <span style='color:#FFB200'>nilai terkecil</span> dalam kolom yang dipilih.</td>
    </tr>
    <tr>
        <td><b>MAX( )</b></td>
        <td>Mengembalikan <span style='color:#FFB200'>nilai terbesar</span> dalam kolom yang dipilih.</td>
    </tr>
    <tr>
        <td><b>COUNT( )</b></td>
        <td>Mengembalikan <span style='color:#FFB200'>jumlah baris</span> dalam suatu set</td>
    </tr>
    <tr>
        <td><b>SUM( )</b></td>
        <td>Mengembalikan <span style='color:#FFB200'>jumlah total</span> dari kolom numerik.</td>
    </tr>
    <tr>
        <td><b>AVG( )</b></td>
        <td>Mengembalikan <span style='color:#FFB200'>nilai rata-rata</span> dari kolom numerik.</td>
    </tr>
</table>

In [2]:
import pandas as pd
import duckdb

# Load semua data
telco_services = pd.read_csv('/content/telco_services.csv')
customer_demography = pd.read_csv('/content/customer_demography.csv')
customer_location = pd.read_csv('/content/customer_location.csv')
customer_status = pd.read_csv('/content/customer_status.csv')
population = pd.read_csv('/content/population.csv')

# Cek apakah data sudah masuk
print("Data telco_services berhasil dimuat!")

Data telco_services berhasil dimuat!

#### <i><b><span style='color:#55679C'>Quest</span> : Hitung banyak data pada tabel telco_services!</b></i>

In [4]:
# Quest: Hitung banyak data
print("Total Data:")
display(duckdb.query("SELECT COUNT(*) AS jumlah_data FROM telco_services").df())

Total Data:

   jumlah_data
0         7043

#### <i><b><span style='color:#55679C'>Quest</span> : Hitung dan tampilkan total_revenue pada  tabel telco_services yang didapat perusahaan!</b></i>

In [5]:
# Quest: Hitung total revenue
print("\nTotal Revenue:")
display(duckdb.query("SELECT SUM(total_revenue) AS total_revenue FROM telco_services").df())

Total Revenue:

   total_revenue
0    21371131.69

#### <i><b><span style='color:#55679C'>Quest</span> : Hitung dan tampilkan nilai minimum, nilai maksimum dan rata-rata kolom tenure_in_months pada tabel telco_services dan beri nama alias yang sesuai!</b></i>

In [6]:
# Quest: Min, Max, dan Rata-rata Tenure
print("\nStatistik Tenure:")
query_tenure = """
SELECT
    MIN(tenure_in_months) AS min_tenure,
    MAX(tenure_in_months) AS max_tenure,
    AVG(tenure_in_months) AS avg_tenure
FROM telco_services
"""
display(duckdb.query(query_tenure).df())

Statistik Tenure:

   min_tenure  max_tenure  avg_tenure
0           1          72   32.386767

#### <i><b><span style='color:#55679C'>Quest</span> : Buat 3 kolom yang diberi total_offer_A_or_B, total_offer_C_or_D_or_E dan non_offer yang merupakan perhitungan</b></i>
<ul>
<li>total_offer_A_or_B = Jumlah customer yang mendapatkan penawaran Offer A atau Offer B</li>
<li>total_offer_C_or_D_or_E = Jumlah customer yang mendapatkan penawaran Offer C, Offer D atau Offer E</li>
<li>non_offer = Jumlah customer yang tidak mendapatkan penawaran</li>
</ul>

In [7]:
query_offer = """
SELECT
    COUNT(CASE WHEN offer IN ('Offer A', 'Offer B') THEN 1 END) AS total_offer_A_or_B,
    COUNT(CASE WHEN offer IN ('Offer C', 'Offer D', 'Offer E') THEN 1 END) AS total_offer_C_or_D_or_E,
    COUNT(CASE WHEN offer IS NULL OR offer = 'None' THEN 1 END) AS non_offer
FROM telco_services
"""
duckdb.query(query_offer).df()

   total_offer_A_or_B  total_offer_C_or_D_or_E  non_offer
0                1344                     1822       3877

<a id="B"></a>
# <b>B. <span style='color:#0B2F9F'><code>GROUP BY</code></b>

Fungsi agregat sering digunakan bersama dengan klausa GROUP BY pada pernyataan SELECT. Klausa GROUP BY membagi hasil query menjadi beberapa kelompok nilai, dan fungsi agregat dapat digunakan untuk mengembalikan satu nilai untuk setiap kelompok.
<br><br>
Contoh simulasi perhitungannya adalah sebagai berikut :
<br><br>
<img src="https://wesmckinney.com/book/images/pda3_1001.png" width="25%" height="1%">

#### <i><b><span style='color:#55679C'>Quest</span> : Hitung dan tampilkan banyaknya customer dari tiap internet_type pada tabel telco_services? Urutkan dari yang jumlahnya terbesar hingga terkecil!</b></i>

In [8]:
# Quest: Customer per internet_type (Urut Terbesar)
query_internet = """
SELECT internet_type, COUNT(customer_id) AS jumlah_customer
FROM telco_services
GROUP BY internet_type
ORDER BY jumlah_customer DESC
"""
display(duckdb.query(query_internet).df())

  internet_type  jumlah_customer
0   Fiber Optic             3035
1           DSL             1652
2          None             1526
3         Cable              830

#### <i><b><span style='color:#55679C'>Quest</span> : Hitung dan tampilkan banyaknya customer tiap kategori offer dan internet_type pada tabel telco_services? Urutkan berdasarkan offer dan internet_type secara ascending!</b></i>

In [9]:
# Quest: Customer per Offer & internet_type (Urut Ascending)
query_mix = """
SELECT offer, internet_type, COUNT(customer_id) AS jumlah_customer
FROM telco_services
GROUP BY offer, internet_type
ORDER BY offer ASC, internet_type ASC
"""
display(duckdb.query(query_mix).df())

      offer internet_type  jumlah_customer
0   Offer A         Cable               68
1   Offer A           DSL              128
2   Offer A   Fiber Optic              232
3   Offer A          None               92
4   Offer B         Cable               92
5   Offer B           DSL              191
6   Offer B   Fiber Optic              379
7   Offer B          None              162
8   Offer C         Cable               51
9   Offer C           DSL               88
10  Offer C   Fiber Optic              195
11  Offer C          None               81
12  Offer D         Cable               57
13  Offer D           DSL              143
14  Offer D   Fiber Optic              237
15  Offer D          None              165
16  Offer E         Cable              111
17  Offer E           DSL              193
18  Offer E   Fiber Optic              328
19  Offer E          None              173
20     None         Cable              451
21     None           DSL              909
22     None   Fiber Optic             1664
23     None          None              853

#### <i><b><span style='color:#55679C'>Quest</span> : Tampilkan kolom phone_internet_type dan total_customer tiap tipe tersebut pada tabel telco_services lalu urutkan dari total_customer terbesar hingga terkecil, dengan ketentuan</b></i><br>
<ul>
<li>Jika customer menggunakan layanan Telepon & Internet, maka phone_internet_type = Phone & Internet</li>
<li>Jika customer menggunakan layanan Telepon namun tidak menggunakan layanan Internet, maka phone_internet_type = Phone Only</li>
<li>Jika customer tidak menggunakan layanan Telepon namun menggunakan layanan Internet, maka phone_internet_type = Internet Only</li>
<li>Jika customer tidak menggunakan kedua layanan tersebut, maka phone_internet_type = No Phone & Internet</li>
</ul>

In [10]:
query_service_type = """
SELECT
    CASE
        WHEN phone_service = 'Yes' AND internet_service = 'Yes' THEN 'Phone & Internet'
        WHEN phone_service = 'Yes' AND internet_service = 'No' THEN 'Phone Only'
        WHEN phone_service = 'No' AND internet_service = 'Yes' THEN 'Internet Only'
        ELSE 'No Phone & Internet'
    END AS phone_internet_type,
    COUNT(customer_id) AS total_customer
FROM telco_services
GROUP BY phone_internet_type
ORDER BY total_customer DESC
"""
duckdb.query(query_service_type).df()

  phone_internet_type  total_customer
0    Phone & Internet            4835
1          Phone Only            1526
2       Internet Only             682

<a id="C"></a>
# <b>C. <span style='color:#0B2F9F'><code>HAVING</code></b>

HAVING dalam SQL digunakan untuk memfilter hasil dari kelompok data yang telah dikelompokkan dengan pernyataan GROUP BY. Mirip dengan klausa WHERE, tetapi HAVING bekerja setelah pengelompokan data dilakukan atau ada agregasi. Dengan kata lain, HAVING biasa digunakan untuk menerapkan kondisi pada hasil agregat.

#### <i><b><span style='color:#55679C'>Quest</span> : Pada tabel telco_services, hitung rata-rata tenure_in_month tiap banyaknya number_of_referrals. Tampilkan data yang rata-rata tenure_in_month kurang dari 40 bulan!</b></i>

In [11]:
# Quest: Rata-rata tenure per referrals < 40 bulan
query_referral = """
SELECT number_of_referrals, AVG(tenure_in_months) AS avg_tenure_in_month
FROM telco_services
GROUP BY number_of_referrals
HAVING avg_tenure_in_month < 40
"""
display(duckdb.query(query_referral).df())

   number_of_referrals  avg_tenure_in_month
0                    0            24.232662
1                    1            36.126151

#### <i><b><span style='color:#55679C'>Quest</span> : Hitung dan tampilkan banyaknya customer tiap kategori offer dan internet_type pada tabel telco_services, namun hanya untuk customer yang menerima offer dan total banyak customer lebih dari sama dengan 100 pada kategori yang telah disebutkan!</b></i>

In [12]:
# Quest: Offer & Internet Type dengan total customer >= 100 (Hanya yang menerima offer)
query_having_offer = """
SELECT offer, internet_type, COUNT(customer_id) AS total_customer
FROM telco_services
WHERE offer IS NOT NULL AND offer != 'None'
GROUP BY offer, internet_type
HAVING total_customer >= 100
ORDER BY offer ASC
"""
display(duckdb.query(query_having_offer).df())

      offer internet_type  total_customer
0   Offer A   Fiber Optic             232
1   Offer A           DSL             128
2   Offer B           DSL             191
3   Offer B   Fiber Optic             379
4   Offer B          None             162
5   Offer C   Fiber Optic             195
6   Offer D   Fiber Optic             237
7   Offer D           DSL             143
8   Offer D          None             165
9   Offer E   Fiber Optic             328
10  Offer E           DSL             193
11  Offer E         Cable             111
12  Offer E          None             173

Data Source : <i>https://www.ibm.com/docs/en/cognos-analytics/11.1.0?topic=samples-telco-customer-churn</i>